### ISSUE TITLE
Full SVD cannot be obtained

### ISSUE THREAD

**Issue by olof3** [JuliaLinearAlgebra/GenericSVD.jl#17]
The following code does not produce a full singular value decomposition.

```
using GenericSVD
F = svd(big.(randn(4,2)), full=true)
```

The problem seems to be in `generic_svdfact!` in `GenericSVD.jl`. In the following code segment
```  
    if sorted
        Idx = sortperm(S,rev=true)
        S = S[Idx]
        U = U[:,Idx]
        Vt = Vt[Idx,:]
    end
```
the last two rows should perhaps be modified to something like
```
        U[:, 1:n] .= U[:,Idx]
        Vt[1:n, :] .= Vt[Idx,:]
```
?

**Comment by kagalenko-m-b** [comment]
Run across this bug myself. This also leads to nullspace() being broken on BigFloat matrices.

Perhaps you could submit a PR, since you've already identified the issue?

**Comment by olof3** [comment]
I was waiting on some feedback to see if the suggested approach seemed reasonable. Do you think it is the right approach?

I haven't looked at this for some time, so if you the possibility feel free to submit a PR, otherwise I'll try to get back to this.

**Comment by kagalenko-m-b** [comment]
I haven't looked at the code myself. But if your PR does not break the tests and the maintainer accepts it, I'd see no reason to doubt it. I think you also identify the deficiency of the tests, because they did not flag the failure of "full" flag, so they might need fixing, as well.

**Comment by kagalenko-m-b** [comment]
Thank you correcting this issue. It seems to me that Pkg.add(GenericSVD) still installs the older version, whereas adding this repository installs the correct version. Any idea when this will propagate to the main repository?

**Comment by simonbyrne** [comment]
I've just tagged a new version: https://github.com/JuliaRegistries/General/pull/11040

**Comment by kagalenko-m-b** [comment]
Great job, thanks!
